version: '3.8'

services:
  exchange-rate-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "5216:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080

      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Information
    restart: unless-stopped
    